name: Comment
'on':
  issue_comment
jobs:
  process_comment:
    name: inspect new comment 
    runs-on:
    - self-hosted
    - Linux
    steps:
    - name: comment debug
      run: echo ${{ github.event.comment.body }}
