name: Debug
'on':
  push:
    branches: prod-br-01 
jobs:
  debug:
    runs-on:
    - self-hosted
    - Linux
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: debug test
      run: bash test.sh

